name: Release Drafter

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Release Drafter
        id: draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name from draft
        run: echo "RELEASE_TAG=${{ steps.draft.outputs.tag_name }}" >> $GITHUB_ENV

      - name: Write release tag to file
        run: |
          mkdir -p build
          echo "${RELEASE_TAG}" > build/release.txt

      - name: Commit and push release tag file
        if: >
          (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'))
          || (github.event_name == 'workflow_dispatch' && (github.event.inputs.branch == 'main' || github.event.inputs.branch == 'master'))
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build/release.txt
          git commit -m "chore: update release tag [skip ci]" || echo "No changes to commit"

          # Fetch latest changes
          git fetch origin main

          # Rebase local changes on top of origin/main
          git rebase origin/main

          # Push updated branch
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
